// Gelin Home — sample property listings data
const PROPERTIES = [
  {
    id: "willow-creek-cottage",
    title: "Willow Creek Cottage",
    price: 425000,
    status: "new",
    type: "House",
    address: "128 Willow Creek Rd",
    city: "Maple Grove",
    beds: 3,
    baths: 2,
    sqft: 1850,
    yearBuilt: 2016,
    lotSize: "0.24 acres",
    image: "assets/images/house-1.svg",
    featured: true,
    description:
      "A bright, updated cottage tucked along Willow Creek with an open-concept kitchen, vaulted living room ceilings, and a covered back porch perfect for morning coffee. Freshly landscaped yard with mature shade trees.",
    features: [
      "Open-concept kitchen with island",
      "Vaulted ceilings in living room",
      "Covered back porch",
      "Attached 2-car garage",
      "Energy-efficient windows",
      "Walking distance to Maple Grove Park",
    ],
    agent: { name: "Amira Hassan", phone: "(555) 210-4471", email: "amira@gelinhome.example" },
  },
  {
    id: "sunset-ridge-retreat",
    title: "Sunset Ridge Retreat",
    price: 612000,
    status: "new",
    type: "House",
    address: "47 Sunset Ridge Dr",
    city: "Brookhaven",
    beds: 4,
    baths: 3,
    sqft: 2620,
    yearBuilt: 2019,
    lotSize: "0.4 acres",
    image: "assets/images/house-2.svg",
    featured: true,
    description:
      "Perched on a gentle rise with sweeping sunset views, this home pairs a chef's kitchen with a spacious primary suite and a finished bonus room ideal for a home office or media space.",
    features: [
      "Chef's kitchen with quartz counters",
      "Primary suite with walk-in closet",
      "Finished bonus room",
      "Fenced backyard with patio",
      "Smart thermostat & lighting",
      "Three-car garage",
    ],
    agent: { name: "Daniel Cho", phone: "(555) 340-9982", email: "daniel@gelinhome.example" },
  },
  {
    id: "harborview-townhome",
    title: "Harborview Townhome",
    price: 349900,
    status: "",
    type: "Townhome",
    address: "9 Harborview Ln, Unit B",
    city: "Port Ellery",
    beds: 2,
    baths: 2.5,
    sqft: 1480,
    yearBuilt: 2012,
    lotSize: "Shared",
    image: "assets/images/house-3.svg",
    featured: true,
    description:
      "Low-maintenance townhome minutes from the harbor with a private rooftop terrace, updated bathrooms, and an attached garage. HOA covers exterior maintenance and landscaping.",
    features: [
      "Private rooftop terrace",
      "Updated bathrooms",
      "Attached 1-car garage",
      "HOA-maintained exterior",
      "Steps from harbor boardwalk",
      "In-unit laundry",
    ],
    agent: { name: "Priya Raman", phone: "(555) 118-7735", email: "priya@gelinhome.example" },
  },
  {
    id: "oakhollow-family-home",
    title: "Oak Hollow Family Home",
    price: 528000,
    status: "",
    type: "House",
    address: "212 Oak Hollow Ct",
    city: "Maple Grove",
    beds: 4,
    baths: 2.5,
    sqft: 2280,
    yearBuilt: 2008,
    lotSize: "0.33 acres",
    image: "assets/images/house-4.svg",
    featured: false,
    description:
      "Set on a quiet cul-de-sac, this family home offers a versatile finished basement, a large deck for entertaining, and a top-rated school district just a short walk away.",
    features: [
      "Finished basement with wet bar",
      "Large entertaining deck",
      "Top-rated school district",
      "Cul-de-sac lot",
      "Newer roof (2021)",
      "Two-car garage with storage loft",
    ],
    agent: { name: "Amira Hassan", phone: "(555) 210-4471", email: "amira@gelinhome.example" },
  },
  {
    id: "birchwood-modern-condo",
    title: "Birchwood Modern Condo",
    price: 279500,
    status: "sold",
    type: "Condo",
    address: "500 Birchwood Ave, Unit 14C",
    city: "Port Ellery",
    beds: 1,
    baths: 1,
    sqft: 890,
    yearBuilt: 2020,
    lotSize: "Shared",
    image: "assets/images/house-5.svg",
    featured: false,
    description:
      "A sleek, low-maintenance condo with floor-to-ceiling windows, a private balcony, and building amenities including a fitness center and rooftop lounge.",
    features: [
      "Floor-to-ceiling windows",
      "Private balcony",
      "Building fitness center",
      "Rooftop lounge access",
      "Secure parking included",
      "In-unit washer/dryer",
    ],
    agent: { name: "Daniel Cho", phone: "(555) 340-9982", email: "daniel@gelinhome.example" },
  },
  {
    id: "meadowbrook-estate",
    title: "Meadowbrook Estate",
    price: 875000,
    status: "new",
    type: "House",
    address: "3 Meadowbrook Way",
    city: "Brookhaven",
    beds: 5,
    baths: 4,
    sqft: 3640,
    yearBuilt: 2021,
    lotSize: "0.6 acres",
    image: "assets/images/house-6.svg",
    featured: true,
    description:
      "An exceptional estate home with soaring ceilings, a dual-island kitchen, a first-floor guest suite, and a resort-style backyard with covered outdoor kitchen.",
    features: [
      "Dual-island gourmet kitchen",
      "First-floor guest suite",
      "Covered outdoor kitchen",
      "Home theater room",
      "Three-car garage",
      "Whole-home generator",
    ],
    agent: { name: "Priya Raman", phone: "(555) 118-7735", email: "priya@gelinhome.example" },
  },
];

function formatPrice(value) {
  return "$" + value.toLocaleString("en-US");
}

function getProperty(id) {
  return PROPERTIES.find((p) => p.id === id);
}
